mypyweb/pyweb/board/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = "board"

urlpatterns = [
   path('', views.question_list, name='question_list'),
   path('<int:question_id>/', views.detail, name='detail'),
   path('question/create/', views.question_create, name='question_create'),
   path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
   path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
   path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
   path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
   path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),

]

mypyweb/pyweb/common/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from common import views

app_name = 'common'

urlpatterns = [
   path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
   path('logout/', auth_views.LogoutView.as_view(), name='logout'),
   path('signup/', views.signup, name='signup'),


]

mypyweb/pyweb/pyweb/urls.py
from django.contrib import admin
from django.urls import path, include

from board import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
]

mypyweb/pyweb/board/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE) #글쓴이
    subject = models.CharField(max_length=200)   #제목
    content = models.TextField()                #질문내용
    create_date = models.DateTimeField()        #등록일
    modify_date = models.DateTimeField(null=True, blank=True) #수정일
    
    def __str__(self):
        return self.subject

#답변 모델(테이블)
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField() #답변 내용
    cteate_date = models.DateTimeField() #등록일
    question = models.ForeignKey(Question, on_delete=models.CASCADE) #외래키
    modify_date = models.DateTimeField(null=True, blank=True)  # 수정일

    def __str__(self):
        return self.content
    

mypyweb/pyweb/common/models.py
from django.db import models

# Create your models here.

mypyweb/pyweb/board/forms.py
from django import forms

from board.models import Question, Answer

from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {'subject': '제목', 'content': '내용'}


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {'content': '답변 내용'}

mypyweb/pyweb/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    username = forms.CharField(max_length=20)
    email = forms.EmailField()
    address = forms.CharField(max_length=50)
    phone = forms.CharField(max_length=20)
    birth = forms.DateField()


    class Meta:
        model = User
        fields = ['username',  'email', 'address', 'phone', 'birth']
        labels = {'username': '사용자이름' ,  'email': '이메일', 'address':'주소', 'phone':'전화번호', 'birth':'생년월일'}

mypyweb/pyweb/board/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from board.forms import QuestionForm, AnswerForm
from board.models import Question, Answer

from django.utils import timezone

from django.contrib.auth.decorators import login_required


def index(request):
   return render(request, 'board/index.html')

   # return HttpResponse("웹페이지 메인입니다.")

def question_list(request):
    question_list= Question.objects.all()
    context= {'question_list':question_list}
    return render(request, 'board/question_list.html',  context)

def detail(request, question_id):
    # question= Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context= {'question':question}
    return render(request, 'board/detail.html', context)

#질문 등록
@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST) #입력된 데이터가 있는 폼
        if form.is_valid(): #폼이 유효하다면(유효성 검사
            question= form.save(commit=False) #가저장
            question.author = request.user #세션 권한 있는 글쓴이
            question.create_date = timezone.now()
            question.save()
            return redirect('board:question_list')

    else:
        form = QuestionForm() #폼객체 생성
    context= {'form':form}
    return render(request, 'board/question_form.html', context) #get 방식


#답변 등록
@login_required(login_url='common:login')
def answer_create(request, question_id):
    #질문이 1개 있어야 답변을 등록할 수 있음
    question= Question.objects.get(id=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer= form.save(commit=False) #content만 저장
            answer.author = request.user  # 세션 권한 있는 글쓴이
            answer.cteate_date = timezone.now()
            answer.question = question #외래키 생성
            answer.save()
            return redirect('board:detail', question_id = question.id)


    else:
        form = AnswerForm()
    context = {'question': question, 'form':form}
    return render(request,  'board/detail.html', context)

#질문삭제
@login_required(login_url='common:login')
def question_delete(request, question_id):
    # question= Question.objects.get(id=question_id)
    # 모델에서 데이터가 있으면 가져오고 없으면 404오류 처리
    question = get_object_or_404(Question, pk=question_id)
    question.delete()
    return redirect('board:question_list')

# 질문 수정
@login_required(login_url='common:login') #로그인 확인-> 로그인이 안되어 있음 login_url로 이동
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method =="POST":
        form = QuestionForm(request.POST, instance= question) #데이터가 이미 있는 폼
        if form.is_valid(): #가저장
            question =form.save(commit=False)
            question.modify_date = timezone.now() #수정일 추가등록
            question.author = request.user # 글쓴이 추가
            question.save()
            return  redirect('board:detail', question_id=question_id)
    else:
        form = QuestionForm(instance=question)
    context= {'form':form}
    return render(request, "board/question_form.html",  context)

# 답변 삭제
@login_required(login_url='common:login') #로그인 확인-> 로그인이 안되어 있음 login_url로 이동
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    answer.delete()
    return redirect('board:detail', question_id=answer.question.id)


# 답변 수정
@login_required(login_url='common:login') #로그인 확인-> 로그인이 안되어 있음 login_url로 이동
def answer_modify(request, answer_id):
    answer = get_object_or_404(Question, pk=answer_id)
    if request.method =="POST":
        form = AnswerForm(instance= answer) #데이터가 이미 있는 폼
        if form.is_valid(): #가저장
            answer = form.save(commit=False)
            answer.modify_date = timezone.now() #수정일 추가등록
            answer.author = request.user # 글쓴이 추가
            answer.save()
            return  redirect('board:detail', question_id=answer.question.id)
    else:
        form = QuestionForm(instance=answer)
    context= {'form':form}
    return render(request, "board/detail.html",  context)

mypyweb/pyweb/common/views.py
from django.shortcuts import render, redirect

from common.forms import UserForm

from django.contrib.auth import authenticate, login


#회원 가입
def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST) #데이터 입력된 폼
        if form.is_valid():
            form.save() #회원가입 db에 저장
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user) #자동로그인
            return redirect('/')
       
    else:
        form = UserForm() #빈폼 생성
    context = {'form':form}

    return render(request, 'common/signup.html', context)

mypyweb/pyweb/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>hello~</title>
    <link rel="stylesheet" href="{% static 'board/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'board/css/style.css'%}">
    <script src="{% static 'board/js/bootstrap.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
</head>
<body>
{% include 'navbar.html' %}
<!--  본문 내용 start-->
{% block content %}

{% endblock %}
<!--본문 내용 end-->

<!-- 제리쿼리 영역-->
{% block script%}

{% endblock%}
</body>
</html>

mypyweb/pyweb/templates/base2.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>hello~</title>
    <link rel="stylesheet" href="{% static 'board/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'board/css/style.css'%}">
    <script src="{% static 'board/js/bootstrap.js' %}"></script>
</head>
<body>
{% include 'navbar.html' %}
<!--  본문 내용 start-->
{% block content %}

{% endblock %}
<!--본문 내용 end-->
</body>
</html>

mypyweb/pyweb/templates/board/123.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  {% if question_list %}
              {% for question in question_list reversed%}
            <div id="wrap">
              <div>{{사진}}</div>
          <div>
                {{forloop.counter}}<div>
              <div>  <a href="{% url 'board:detail' question.id %}">{{question.subject}}</a></div>

                <td>{{question.create_date}}</td>
               </div>

</body>
</html>

mypyweb/pyweb/templates/board/detail.html
{% extends 'base.html' %}
{% block content %}
<div class ="container my-3">
    <section id="detail">

  <h2 class="border-bottom py-2"> {{question.subject}}</h2>
  <div class="card my-3">
      <div class="card-body">
          <div class="card-text">
              {{question.content}}
          </div>
          <div class="d-flex justify-content-end">
              <div class="badge bg-info text-start">
                  <div class="mb-2">{{question.author}}</div>
                  <div>{{question.create_date}}</div>
              </div>

          </div>
      </div>
  </div>
<!--        글쓴이와 로그인한 사람이 일치하면-->
    {% if question.author == request.user %}
        <div>
            <a href="{% url 'board:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary"> 수정</a>
            <a href="#"
               data-uri="{% url 'board:question_delete' question.id %}"

            class="delete btn btn-sm btn-outline-secondary">삭제</a>
        </div>
        {% endif %}

  <h5 class="border-bottom my-3 py-2" >{{question.answer_set.count}}개 답변이 있습니다.</h5>


            {% for answer in question.answer_set.all %}
    <div class="card my-3">
      <div class="card-body">
          <div class="card-text" style="white-space: pre-line">
             {{ answer.content}}
          </div>
            <div class="d-flex justify-content-end">
              <div class="badge bg-info text-start">
                  <div class="mb-2">{{answer.author}}</div>
                  <div>{{answer.cteate_date}}</div>
              </div>

          </div>
          <!--        글쓴이와 로그인한 사람이 일치하면-->
    {% if answer.author == request.user %}
        <div>
            <a href="{% url 'board:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary"> 수정</a>
            <a href="#"
               data-uri="{% url 'board:answer_delete' answer.id %}"

               class="delete btn btn-sm btn-outline-secondary">삭제</a>
        </div>
        {% endif %}
      </div>
  </div>
            {% endfor %}


    <!-- 답변 등록 폼-->
    <form action="{% url 'board:answer_create' question.id %}" method="post">
        {% csrf_token %}
        {% include 'form_errors.html'%}
        <div class="form-group">
                <textarea name="content" rows="10" cols="50" class="form-control mb-3"
                {% if not user.is_authenticated %} disabled {%endif%}> </textarea>
                <button type="submit" class="btn btn-primary">답변등록</button>
        </div>

    </form>
        </section>
    </div>

{% endblock %}
{% block script%}
<script>
    $(document).ready(function(){
        $('.delete').click(function(){
            if(confirm('정말 삭제하시겠습니까?')){
                location.href=$(this).data('uri'); //현재 uri 대상의 주소로 이동
            }
        });
    });
</script>
{% endblock%}

mypyweb/pyweb/templates/board/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="container my-3">
  <h1> pyweb에 오신걸 환경합니다.</h1>
        </div>

{% endblock %}

mypyweb/pyweb/templates/board/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <section id="question_form">
        <h4 class = "border-bottom">질문 등록</h4>
        <form action="" method="post">
         {% csrf_token %}
<!--      {{ form.as_p }}-->
<!--            오효성 검사 오류 처리시작-->
            {% if form.errors %}    <!--폼을 필드를 순회하면서-->
                <div class="alert alert-danger"> <!--필드에 오류가 있으면-->
                {% for field in form %}
                    {% if field.errors %}
                        {{ field.label}}
                        {{field.errors}}  <!--에러 출력-->
                    {% endif %}
                {% endfor %}
                </div>
            {%endif%}
<!--            오류 처리 끝-->
             <div class="form-group">
                 <label for="subject">제목</label>
                 <input type="text" id="subject" name="subject" class="form-control"
                        value="{{form.subject.value|default_if_none:''}}">
             </div>
             <div class="form-group">
                 <label for="content">내용</label>
                <textarea name="content" id="content" rows="10" cols="50" class="form-control">{{form.content.value|default_if_none:''}}  </textarea>

        </div>
      <button type="submit" class="btn btn-primary"> 전송</button>
  </form>

    </section>

</div>


{% endblock %}

mypyweb/pyweb/templates/board/question_list.html
{% extends 'base.html'%}
{% block content %}


    <div class="container my-3">

    <section id="question_list">
        <h2 class="border-bottom py-2">질문목록</h2>
        <table class="table">
            <thead>
            <tr class="table-danger">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
                <th>글쓴이</th>
            </tr>
            </thead>
            <tbody>
            {% if question_list %}
              {% for question in question_list reversed%}
            <tr>
                <td>{{forloop.counter}}</td>
                <td><a href="{% url 'board:detail' question.id %}">{{question.subject}}</a></td>
                <td>{{question.create_date}}</td>
                <td>{{question.author}}</td>

            </tr>
                {% endfor %}
             {% else %}
        <p>질문이 없습니다.</p>
            {% endif %}
            </tbody>
        </table>

 <a href="{% url 'board:question_create'%}"><button class="btn btn-primary">질문등록</button></a>
    </section>
    </div>






{% endblock %}

mypyweb/pyweb/templates/common/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <section id="login">
    <div class="row">
      <div class = "col-4">
         <h4>로그인</h4>
      </div>
      <div class ="col-8 text-end">
      </div>
    </div>
<!--  로그인 폼 -->
  <form action="" method="post">
    {% csrf_token %}

    <div class="form-group">
      <label for="username">사용자ID</label>
      <input type="text" id="username" name="username" class="form-control"
      value="{{form.username.value|default_if_none:''}}">
    </div>
     {% include 'form_errors.html' %}
    <div class="form-group">
      <label for="password">비밀번호</label>
      <input type="password" id="password" name="password" class="form-control"
      value="{{form.password.value|default_if_none:''}}">
    </div>
    <button type="submit" class="btn btn-primary mt-2">로그인</button>
   <a href="{% url 'common:signup' %}"> <button type="button" class="btn btn-primary mt-2">회원가입</button></a>

  </form>



  </section>
</div>


{% endblock%}

mypyweb/pyweb/templates/common/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

mypyweb/pyweb/templates/form_errors.html
<!--            오효성 검사 오류 처리시작-->
            {% if form.errors %}    <!--폼을 필드를 순회하면서-->
                <div class="alert alert-danger"> <!--필드에 오류가 있으면-->
                {% for field in form %}
                    {% if field.errors %}
                        {{ field.label}}
                        {{field.errors}}  <!--에러 출력-->
                    {% endif %}
                {% endfor %}
                </div>
            {%endif%}
<!--            오류 처리 끝-->

mypyweb/pyweb/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Pyweb</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'board:question_list'%}">질문&답변</a>
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'common:logout' %}">({{user.username }})로그아웃</a>
          {% else %}
           <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
          {% endif %}
        </li>
           </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</body>
</html>

mypyweb/pyweb/templates/navbar2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</body>
</html>