mypyweb/blogs/blog/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:post_id>', views.detail, name='detail'),
    path('category/<str:sug>/', views.category_page, name='category_page'),
]

mypyweb/blogs/common/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from common import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'),  name='login'),
    path('logout/', auth_views.LogoutView.as_view(),  name='logout'),
    path('signup/', views.signup,  name='signup'),

]

mypyweb/blogs/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('blog/', include('blog.urls')),
    path('common/', include('common.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mypyweb/blogs/blog/models.py
from django.db import models


# 카테고리 모델
class Category(models.Model):
    # unique 중복불허
    name = models.CharField(max_length=50, unique=True)

    # url-주소 allow_unicode 한글허용
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    # 카테고리 url 주소
    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'

    # 관리자 페이지에서 적용-verbose_name_plural 복수형
    class Meta:
        ordering = ['name']  # 이름순 정렬
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class Post(models.Model):
    title = models.CharField(max_length=200) #제목
    content  = models.TextField() #내용
    pub_date = models.DateTimeField() #발행일
    modify_date = models.DateTimeField(null=True, blank=True)
    photo = models.ImageField(upload_to='blog/post/%Y/%m/%d/', null=True, blank=True)
    category = models.ForeignKey(Category, null=True, blank=True , on_delete=models.CASCADE)

    def __str__(self):
        return self.title

mypyweb/blogs/common/models.py
from django.db import models

# Create your models here.

mypyweb/blogs/blog/views.py
from django.shortcuts import render

from blog.models import Post, Category


def index(request):
    return render(request, 'blog/index.html')

def post_list(request):
    post_list = Post.objects.all()
    categories = Category.objects.all()
    context = {'post_list':post_list, 'categories': categories}
    return render(request, 'blog/post_list.html', context)

def detail(request, post_id):
    post = Post.objects.get(id=post_id)
    context = {'post':post}
    return render(request, 'blog/detail.html', context)

#카테고리 페이지 처리 메서드
def category_page(request, slug) :
    current_category = Category.object.get(slug=slug) #현재 카테고리 검색
    post_list = Post.object.filter(category=current_category) #현 카테고리의 검색
    post_list = post_list.order_by('-pub_date') #날짜순 정렬
    categories = Category.objects.all() #전체키워드 탐색
    context = {'post_list':post_list, 'current_category':current_category,  'categories':categories}
    return render(request, 'blog/post_list.html', context)

mypyweb/blogs/common/views.py
from django.shortcuts import render, redirect
from blog.form import UserForm
def signup(request):
    if request.method == "POST":

        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = UserForm()
    context = {'form':form}
    return render(request, 'common/signup.html', context)

mypyweb/blogs/templates/base.html
<!DOCTYPE html>
<html lang="en">
{%load static%}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Blog{% endblock%}</title>
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css'%}">
    <script src="{% static 'blog/css/bootstrap.js'%}"></script>

</head>
<body>
<!-- base -->
{% include 'navbar.html'%}
{% block content %}

{% endblock%}
<!-- base -->
</body>
</html>

mypyweb/blogs/templates/blog/detail.html
{% extends 'base.html'%}
{% block content%}
<div class="container">
    <h1> blog 홈</h1>


    <h3>{{post.title}}</h3>
    <h4 style="white-space: pre-line; line-height: 1.5em">{{post.content}}</h4>
    <h5>(작성일:{{post.pub_date}})</h5>




</div>
{% endblock%}

mypyweb/blogs/templates/blog/index.html
{% extends 'base.html'%}{%load static%}
{% block content%}
<div class="container">
    <h1> blog에 오신 것을 환영합니다.</h1>
    <video src="{% static 'blog/images/abc.mp4' %}" autoplay muted loop width="100%"></video>
</div>
{% endblock%}

mypyweb/blogs/templates/blog/post_list.html
{% extends 'base.html'%}
{%block title %} 포스트 목록입니다.
{%endblock%}
{% block content%}
<div class="container">

    {% if post_list %}
<!-- 포스트 리스트가 있다면-->
    {% for post in post_list %}
    <h3><a href="{% url 'blog:detail' post.id %}"> {{post.title}}</a></h3>
    <h4 style="white-space: pre-line; line-height: 1.5em">{{post.content}}</h4>
    <h5>(작성일:{{post.pub_date}})</h5>
    {% if post.photo %}
                <img src="{{ post.photo.url }}">
            {% endif %}
    {%endfor%}
    {% else %}
<!-- 포스트 리스트가 없다면-->
    <p> 포스트가 없습니다.</p>
    {%endif%}
    <aside>
        <h4>분류     </h4>
        <ul>
        {%for category in categories%}
            {% if current_category.slug == category.slug %}

            <a href="{{category.get_absoulute_url}}">   <li style="background: #ff0">{{category.name}}({{category.post_set.count}})</li></a>
            {%else%}
              <a href="{{category.get_absoulute_url}}">   <li>{{category.name}}({{category.post_set.count}})</li></a>
            {%endif%}

          {%endfor%}
            </ul>
    </aside>


</div>
{% endblock%}

mypyweb/blogs/templates/common/login.html
{% extends 'base.html' %}
{%block title %} 로그인 폼
{%endblock%}
{% block content %}
<div class="container">
  <section id="login">
    <div class="row">
      <div class = "col-4">
         <h4>로그인</h4>
      </div>
      <div class ="col-8 text-end">
      </div>
    </div>
<!--  로그인 폼 -->
  <form action="" method="post">
    {% csrf_token %}
{% include 'form_errors.html' %}
    <div class="form-group">
      <label for="username">사용자ID</label>
      <input type="text" id="username" name="username" class="form-control"
      value="{{form.username.value|default_if_none:''}}">
    </div>

    <div class="form-group">
      <label for="password">비밀번호</label>
      <input type="password" id="password" name="password" class="form-control"
      value="{{form.password.value|default_if_none:''}}">
    </div>
    <button type="submit" class="btn btn-primary mt-2">로그인</button>
   <a href="{% url 'common:signup'%}"> <button type="button" class="btn btn-primary mt-2">회원가입</button></a>

  </form>



  </section>
</div>
{% endblock %}

mypyweb/blogs/templates/common/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <section id="signup">
    <div class="row">
      <div class = "col-4">
         <h4>회원가입</h4>
      </div>
      <div class ="col-8 text-end">
      </div>
    </div>
          <form method="post" action="">
        {% csrf_token %}
        {% include 'form_errors.html' %}

        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="email" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
       <div class="mb-3">
            <label for="address">주소</label>
            <input type="text" class="form-control" name="address" id="address"
                   value="{{ form.address.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="phone">전화번호</label>
            <input type="text" class="form-control" name="phone" id="phone"
                   value="{{ form.phone.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="birth">생년월일</label>
            <input type="text" class="form-control" name="birth" id="birth"
                   value="{{ form.birth.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
        <a href="{% url 'common:login' %}"><button type="button" class="btn btn-primary">로그인하기</button></a>

    </form>

  </section>
</div>

{% endblock %}

mypyweb/blogs/templates/form_errors.html
<!-- 유효성 검사 - 오류 처리 시작-->
{% if form.errors  %}
    {% for field in form %}  <!-- 폼을 필드를 순회하면서 -->
        {% if field.errors  %} <!-- 필드에 오류가 있으면 -->
        <div class="alert alert-danger">
            <strong>{{ field.label }}</strong>
            {{ field.errors }}  <!-- 에러 출력 -->
         </div>
        {% endif %}
    {% endfor %}

    <!-- 넌 필드 오류-->
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}
<!-- 오류 처리 끝-->

mypyweb/blogs/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{%url 'blog:post_list'%}">Home</a>
        </li>
        {% if not user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link" href="{%url 'common:login'%}">로그인</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{%url 'common:login'%}">로그아웃</a>
        </li>
        {%endif%}

        <li class="nav-item">
          <a class="nav-link" href="{%url 'blog:post_list'%}">블로그</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">글쓰기\
          </a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>