mypyweb/polls/config/urls.py
from django.contrib import admin
from django.urls import path, include

from poll import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/' , include('poll.urls')),
    path('', views.index),
]

mypyweb/polls/poll/urls.py
from django.urls import path
from .import views
#네임스페이스(이름 공간)
app_name = 'poll'

urlpatterns = [
    #http://127.0.0.1:8000/poll/
    path('', views.poll_list,  name='poll_list'),

    #http://127.0.0.1:8000/poll/?
    path('<int:question_id>/', views.detail, name='detail'),

    #http://127.0.0.1:8000/poll/?/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

    #http://127.0.0.1:8000/poll/test/
    path('test/', views.test, name='test'),


]

mypyweb/polls/poll/models.py
from django.db import models

from django.utils import timezone


# Create your models here.
class Question(models.Model):
    # 필드

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    def __str__(self):  # 객체 정보를 문자열로 반환
        return self.question_text


# 항목 테이블(엔티티)
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mypyweb/polls/poll/views.py
from django.http import HttpResponse
from django.shortcuts import render
from poll.models import Question


def index(request):
    return render(request, 'poll/index.html')

# Create your views here.
def poll_list(request):
    question_list = Question.objects.all()
    return render(request, 'poll/poll_list.html', {'question_list': question_list})
    # return HttpResponse("<h1>안녕~~! Django</h1>")


def test(request):
    cart = "계란"  # 모델(데이터) - 딕셔너리형으로 보냄
    cartlist = ["계란", "콩나물", "칫솔", "치약", "햇반", "고구마", "닭도리탕", "칼국수", "샤브샤브"]
    context = {'cart': cart, 'cartlist': cartlist}
    return render(request, 'poll/test.html', context)


def detail(request, question_id):
    question = Question.objects.get(id=question_id)
    return render(request, 'poll/detail.html', {'question': question})

def vote(request, question_id):
    question = Question.objects.get(id=question_id)
    if request.method == "POST":
        try:
            choice_id = request.POST['choice'] #선택된 항목 아이디
            sel_choice = question.choice_set.get(id=choice_id) #아이디로 항목을 찾아서
        except:
            error = "선택을 하지 않았습니다."
            return render(request, 'poll/detail.html', {'question': question, 'error': error})
        else:
            sel_choice.votes += 1
            sel_choice.save() #저장 필수
            return render(request, 'poll/result.html', {'question': question})
    else:
        return render(request, 'poll/detail.html', id=question_id)

mypyweb/polls/templates/poll/detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <title>설문 항목</title>
</head>
<body>
    <h1> 설문 항목</h1>

    <div id="container">
        <section id="detail">
    <form action="{% url 'poll:vote' question.id%}" method="post">
    {% csrf_token %} <!--해킹 방지-->

        <fieldset>
            {% if error %}
                <p class="error"> {{error}}</p>
            {%endif%}
            <legend>{{question.question_text}}</legend>
            {% for choice in question.choice_set.all %}
            <p>
                <input type="radio" name="choice" value="{{choice.id}}">
                <label>{{choice.choice_text }}</label>

            </p>
             {% endfor %}
        </fieldset>
     <input type="submit" value="투표">


    </form>
            </section>
        </div>



</body>
</html>

mypyweb/polls/templates/poll/index.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>main 페이지</title>
    <link rel="stylesheet" href="{% static 'poll/css/style.css'%}">
</head>
<body>
    <div id="container">
        <section id="main">
            <div class="poll">
                <a href="{%url 'poll:poll_list' %}">
                    <img src="{% static 'poll/images/vote.JPG' %}" alt="투표">
                    <p>설문 투표 바로가기</p>
                </a>
            </div>
            <div class="ocr">
                <a href="">
                    <img src="{% static 'poll/images/ocr.png' %}" alt="투표">
                    <p>설문 투표 바로가기</p>
                </a>
            </div>


        </section>
    </div>
</body>
</html>

mypyweb/polls/templates/poll/poll_list.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>main 페이지</title>
    <link rel="stylesheet" href="{% static 'poll/css/style.css'%}">
</head>
<body>
<div id="container">
    <section id="poll_list">
    <h1>설문 목록</h1>

    <!--<h3> {{question_list}}</h3>-->
    {% if question_list %}
    <ul>
        {% for question in question_list %}
        <li>
            <a href="{% url 'poll:detail' question.id%}">
            {{question.question_text}}
            </a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p> 설문이 없습니다.</p>
    {% endif%}
    <img src="{% static 'poll/images/vote.JPG'%}">
</section>
</div>
</body>
</html>

mypyweb/polls/templates/poll/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>투표 결과</title>
</head>
<body>
    <h1>투표 결과</h1>

    <h3>{{ question.question_text}}</h3>
    <ul>
        {% for choice   in question.choice_set.all %}
        <li>{{choice.choice_text}}-- {{choice.votes}}</li>

        {% endfor%}
    </ul>
</body>
</html>

mypyweb/polls/templates/poll/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3> {{cart}}</h3>
        <ul>
            {% for cart1 in cartlist %}
            <li>{{cart1}}</li>
            {% endfor %}
        </ul>
</body>
</html>